name: Build and Test Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run tests
        run: mvn test
